# -*- coding: utf-8 -*-
"""funçoes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwPw_lhLZuuGdmbmI3nHC7HZcfM5YKYY
"""

def processar_vendas():

  total = 0.0

  itens = 0

  quantidade = int(input("Quantos produtos diferentes você comprou? "))

  for i in range(quantidade):

    print("\nProduto", i + 1)

    nome = input("Nome do produto: ")

    preco = float(input("Preço unitário: R$ "))

    qtd = int(input("Quantidade: "))

    if preco <= 0 or qtd <= 0:

      print("Valores inválidos para", nome, "- pulando...")

    else:

      subtotal = preco * qtd

      total = total + subtotal

      itens = itens + qtd

      print("Subtotal:", subtotal)

  if total > 500:

    total_com_desconto = total * 0.90

    print("\nDesconto de 10% aplicado!")

  elif total > 200:

    total_com_desconto = total * 0.95

    print("\nDesconto de 5% aplicado!")

  else:

    total_com_desconto = total

    print("\nSem desconto.")

  print("Total de itens:", itens)

  print("Total a pagar: R$", round(total_com_desconto, 2))

def analisar_clima():

  soma = 0.0

  dias_quentes = 0

  alerta = False

  for dia in range(1, 8):

    temp = float(input("Temperatura do dia " + str(dia) + ": "))

    soma = soma + temp

    if temp > 35:

      dias_quentes = dias_quentes + 1

    if temp > 45 or temp < -5:

      alerta = True

  media = soma / 7

  print("\nMédia da semana:", round(media, 1), "°C")

  print("Dias acima de 35°C:", dias_quentes)

  if alerta:

    print("ATENÇÃO: temperatura perigosa detectada!")

  else:

    print("Clima normal na semana.")

def sistema_notas_turma():

  total_alunos = int(input("Quantos alunos tem na turma? "))

  for j in range(total_alunos):

    print("\nAluno", j + 1)

    nome = input("Nome do aluno: ")

    n1 = float(input("Nota 1: "))

    n2 = float(input("Nota 2: "))

    media = (n1 + n2) / 2

    if media >= 7:

      print(nome, "- Aprovado! Média:", round(media, 1))

    elif media >= 5:

      print(nome, "- Recuperação. Média:", round(media, 1))

    else:

      print(nome, "- Reprovado. Média:", round(media, 1))

def sistema_notas_turma():

  total_alunos = int(input("Quantos alunos tem na turma? "))

  for j in range(total_alunos):

    print("\nAluno", j + 1)

    nome = input("Nome do aluno: ")

    n1 = float(input("Nota 1: "))

    n2 = float(input("Nota 2: "))

    media = (n1 + n2) / 2

    if media >= 7:

      print(nome, "- Aprovado! Média:", round(media, 1))

    elif media >= 5:

      print(nome, "- Recuperação. Média:", round(media, 1))

    else:

      print(nome, "- Reprovado. Média:", round(media, 1))

def simulador_poupanca():

  saldo = float(input("Valor inicial: R$ "))

  taxa = float(input("Taxa de juros mensal (%): "))

  meses = int(input("Quantos meses quer simular? "))

  for m in range(1, meses + 1):

    aporte = float(input("\nMês " + str(m) + " - Quanto vai depositar? R$ "))

    saldo = saldo + aporte

    juros = saldo * (taxa / 100)

    saldo = saldo + juros

    print("Saldo no mês", m, ": R$", round(saldo, 2))

    if saldo >= 10000:

      print("Parabéns! Você passou de R$10.000 no mês", m)

  print("\nSaldo final após", meses, "meses: R$", round(saldo, 2))