# -*- coding: utf-8 -*-
"""30/04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ssjI77VNyudRO10B9iCWrhaUbla3yT6u
"""

LIMITE_SEGURANCA = 10000.00
def analisar_vendas(venda_1, venda_2, venda_3):
    # Palavra-chave global para poder alterar a variável lá de cima
    global LIMITE_SEGURANCA
    # Calculando a média simples
    media = (venda_1 + venda_2 + venda_3) / 3
    # Mostrando os valores e seus tipos (casting)
    print("Venda 1:", venda_1, "| tipo:", type(venda_1))
    print("Venda 2:", venda_2, "| tipo:", type(venda_2))
    print("Venda 3:", venda_3, "| tipo:", type(venda_3))
    print("Média:", media)
    print("Limite de segurança:", LIMITE_SEGURANCA)
    # mudar o limite de segurança
    resposta = input("Deseja alterar o LIMITE_SEGURANCA? (sim/nao): ")
    if resposta == "sim":
        LIMITE_SEGURANCA = float(input("Novo limite: "))
        print("Limite atualizado para:", LIMITE_SEGURANCA)
    # Verificação 1: média acima do limite?
    if media > LIMITE_SEGURANCA:
        print("ALERTA: SISTEMA EM QUARENTENA")
    # Verificação 2: alguma venda é 5x maior que a média?
    if venda_1 > media * 5 or venda_2 > media * 5 or venda_3 > media * 5:
        print("ALERTA: REVISÃO MANUAL")

# Entrada de dados — float() faz o casting de texto para número decimal
venda_1 = float(input("Digite o valor da venda 1: "))
venda_2 = float(input("Digite o valor da venda 2: "))
venda_3 = float(input("Digite o valor da venda 3: "))
analisar_vendas(venda_1, venda_2, venda_3)