# -*- coding: utf-8 -*-
"""conceitos-de-lista

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvj_jtydst7zUKdim-b5vaHNsw6sst7k
"""

# Parte 1 - Microclima Urbano

# Coletei dados de 4 pontos do meu trajeto diário em São Paulo

# Fonte: CETESB e Climatempo, medidos de manhã (~8h) e de tarde (~15h)

# Cada item da lista tem: [nome do local, horario, temperatura, umidade, IQA]

dados_locais = [

  ["Parque Ibirapuera",   "Manha", 21, 75, 35],

  ["Parque Ibirapuera",   "Tarde", 26, 60, 42],

  ["Av. 23 de Maio",    "Manha", 24, 66, 88],

  ["Av. 23 de Maio",    "Tarde", 32, 45, 115],

  ["Ponto Radial Leste",  "Manha", 23, 69, 63],

  ["Ponto Radial Leste",  "Tarde", 31, 50, 80],

  ["Trabalho - Barra Funda", "Manha", 25, 62, 95],

  ["Trabalho - Barra Funda", "Tarde", 33, 43, 128],

]


# Loop principal: passa por cada local da lista

for local in dados_locais:


  # Pego cada informação pelo índice da lista

  nome    = local[0]

  horario  = local[1]

  temperatura = local[2]

  umidade  = local[3]

  iqa    = local[4]

  print("--------------------")

  print("Local:   " + nome)

  print("Horario:  " + horario)

  print("Temperatura: " + str(temperatura) + " graus")

  print("Umidade:  " + str(umidade) + "%")

  print("IQA:    " + str(iqa))


  # Classifica a qualidade do ar pelas faixas oficiais da CETESB

  match True:

    case _ if iqa <= 40:

      qualidade = "Boa"

    case _ if iqa <= 80:

      qualidade = "Moderada"

    case _ if iqa <= 120:

      qualidade = "Ruim"

    case _ if iqa <= 200:

      qualidade = "Muito Ruim"

    case _:

      qualidade = "Pessima"

  print("Qualidade do ar: " + qualidade)


  # Calculo a nota de conforto (0 a 10)

  # Temperatura ideal pra mim: entre 20 e 26 graus

  if 20 <= temperatura <= 26:

    nota_temp = 10

  elif temperatura < 20:

    nota_temp = 10 - (20 - temperatura) * 1.5

  else:

    nota_temp = 10 - (temperatura - 26) * 1.2


  # Garante que a nota nao passa de 0 pra baixo

  if nota_temp < 0:

    nota_temp = 0


  # Umidade ideal: entre 50% e 70%

  if 50 <= umidade <= 70:

    nota_umidade = 10

  elif umidade < 50:

    nota_umidade = 10 - (50 - umidade) * 0.4

  else:

    nota_umidade = 10 - (umidade - 70) * 0.3

  if nota_umidade < 0:

    nota_umidade = 0



  # IQA: quanto menor o IQA, melhor. Converto em nota invertida

  nota_iqa = 10 - (iqa / 200) * 10

  if nota_iqa < 0:

    nota_iqa = 0



  # Nota final com pesos: temperatura 40%, umidade 30%, IQA 30%

  nota_final = (nota_temp * 0.4) + (nota_umidade * 0.3) + (nota_iqa * 0.3)

  nota_final = round(nota_final, 1)

  print("Nota de conforto: " + str(nota_final) + "/10")


  # Dou um veredicto baseado na nota
  if nota_final >= 7:

    print("Situacao: bom pra caminhar, sem problema nenhum.")

  elif nota_final >= 4:

    print("Situacao: da pra aguentar, mas quem tem asma ou rinite sofre.")

  else:

    print("Situacao: ruim demais, prefiro esperar dentro de algum lugar.")

print("--------------------")

print("Analise concluida.")

# Parte 2 - Simulador de Evacuacao

# Mapeei o 1 andar da UNICID.

# O agente tenta sair da sala do fundo ate a calcada da Rua Cesario Galeno.

# Lista 1: os lugares do trajeto que identifiquei

locais = [

  "Sala de aula - fundo do corredor (1 andar)",

  "Corredor principal do 1 andar",

  "Copa com cadeiras empilhadas",

  "Porta corta-fogo",

  "Base da escada de saida",

  "Corredor do terreo",

  "Porta de saida lateral",

  "Calcada - Rua Cesario Galeno (SAIDA)"

]


# Lista 2: o que tem em cada lugar (mesma ordem da lista acima)

situacoes = [

  "livre",

  "extintor na parede",

  "cadeiras bloqueando passagem",

  "trava magnetica - precisa de cracha",

  "cracha de emergencia na caixinha",

  "fumaca leve no corredor",

  "barra antipânico",

  "saida"

]


# Inventario e estado do agente

inventario  = []

energia   = 18

posicao   = 0 # começa na posição 0 (sala de aula)

print("Inicio: " + locais[posicao])

print("Energia: " + str(energia))

print("==========================")


# Loop while: continua enquanto nao chegou na saida e ainda tem energia

while posicao < len(locais) - 1 and energia > 0:

  lugar  = locais[posicao]

  situacao = situacoes[posicao]

  print("\nAgente em: " + lugar)

  print("Situacao: " + situacao)

  print("Energia: " + str(energia))

  print("Inventario: " + str(inventario))


  # Avalia o que tem naquele lugar e decide o que fazer

  if situacao == "livre":

    print("-> Caminho livre. Seguindo em frente.")

    posicao = posicao + 1

    energia = energia - 1


  elif situacao == "extintor na parede":

    print("-> Peguei o extintor. Pode ser util la na frente.")

    inventario.append("extintor")

    posicao = posicao + 1

    energia = energia - 1


  elif situacao == "cadeiras bloqueando passagem":

    if energia >= 4:

      print("-> Tinha cadeiras no caminho. Empurrei e passei.")

      posicao = posicao + 1

      energia = energia - 3

    else:

      print("-> Pouca energia, mas tentei passar pela lateral. Deu.")

      posicao = posicao + 1

      energia = energia - 1



  elif situacao == "trava magnetica - precisa de cracha":

    if "cracha" in inventario:

      print("-> Passei o cracha na trava. Porta abriu.")

      inventario.remove("cracha")

      posicao = posicao + 1

      energia = energia - 1

    else:

      # Nao tem cracha — verifica se tem extintor pra forcar

      if "extintor" in inventario:

        print("-> Sem cracha! Usei o extintor pra forcar a trava. Abriu.")

        inventario.remove("extintor")

        posicao = posicao + 1

        energia = energia - 4

      else:

        print("-> Sem cracha e sem extintor. Preciso voltar buscar.")

        posicao = posicao - 1

        energia = energia - 4


  elif situacao == "cracha de emergencia na caixinha":

    print("-> Achei o cracha de emergencia na caixinha da parede!")

    inventario.append("cracha")

    posicao = posicao + 1

    energia = energia - 1


  elif situacao == "fumaca leve no corredor":

    if "extintor" in inventario:

      print("-> Tinha fumaca. Usei o extintor pra abrir caminho.")

      inventario.remove("extintor")

      posicao = posicao + 1

      energia = energia - 1

    else:

      print("-> Fumaca sem extintor. Agachei e passei devagar.")

      posicao = posicao + 1

      energia = energia - 3



  elif situacao == "barra antipânico":

    if energia >= 3:

      print("-> Empurrei a barra antipanico com o ombro. Abriu.")

      posicao = posicao + 1

      energia = energia - 3

    else:

      print("-> Quase sem energia, mas bati na barra. Abriu!")

      posicao = posicao + 1

      energia = 0


# Verifica se conseguiu ou nao sair

print("\n==========================")

if posicao >= len(locais) - 1:

  print("CONSEGUIU SAIR!")

  print("Chegou em: " + locais[posicao])

  print("Energia que sobrou: " + str(energia))

else:

  print("NAO CONSEGUIU SAIR.")

  print("Ficou sem energia em: " + locais[posicao])