# -*- coding: utf-8 -*-
"""sistema-de-auditoria-de recursos-corporativos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcrJQo2Uc9wqEYVPGEWMvfsC5FuMKCHX
"""

import time

empresa_data = {
    "Matriz": {
        "TI": {
            "Infraestrutura": {
                "Servidores": 50000,
                "Seguranca": 30000
            },
            "Desenvolvimento": {
                "Frontend": 20000,
                "Backend": 25000,
                "DevOps": 15000
            }
        },
        "RH": {
            "Recrutamento": 10000,
            "Treinamento": 12000,
            "Cultura": {
                "Eventos": 5000,
                "Brindes": 2000
            }
        },
        "Financeiro": 40000
    }
}


# Decorator de auditoria
def auditor(funcao_original):
    def embrulho(*args, **kwargs):
        print("\n========== INICIO DA AUDITORIA ==========")
        print(f"Funcao chamada: {funcao_original.__name__}")
        print(f"Departamentos ignorados: {args[1:]}")
        print(f"Parametros de conversao: {kwargs}")

        inicio = time.time()
        resultado = funcao_original(*args, **kwargs)
        fim = time.time()

        print(f"Tempo de execucao: {fim - inicio:.5f} segundos")
        print("=========================================\n")
        return resultado
    return embrulho


@auditor
def calcular_orcamento(estrutura, *args, **kwargs):

    departamentos_ignorados = args

    taxa = kwargs.get("taxa_cambio", 1)
    moeda = kwargs.get("moeda_destino", "BRL")

    def somar(no):
        if isinstance(no, (int, float)):
            return no

        total = 0
        for nome, conteudo in no.items():
            if nome in departamentos_ignorados:
                print(f"  [IGNORADO] {nome}")
                continue
            total = total + somar(conteudo)
        return total

    total_bruto = somar(estrutura)
    total_final = total_bruto * taxa

    print(f"\n  Total em BRL : R$ {total_bruto}")
    print(f"  Total em {moeda}  : {total_final}")

    return total_final

print("--- Orcamento total da empresa ---")
calcular_orcamento(empresa_data)

print("--- Ignorando o departamento de TI ---")
calcular_orcamento(empresa_data, "TI")

print("--- Convertendo para USD ---")
calcular_orcamento(empresa_data, moeda_destino="USD", taxa_cambio=0.19)

print("--- Ignorando RH e convertendo para EUR ---")
calcular_orcamento(empresa_data, "RH", moeda_destino="EUR", taxa_cambio=0.17)